### PR TITLE
Integrate Turris Omnia 2019.07 u-boot + generate sysupgrade image

### PR DESCRIPTION
**Pull request by fifalars**
This merge request is twofold:

The first commit adds:
- **u-boot 2019.07** directly from the CZ.NIC gitlab: https://gitlab.nic.cz/turris/turris-omnia-uboot/-/tree/omnia-2019
This replaces Marvell u-boot that has been currently used (2017.03). Keep in mind this does *not* provide the entire mtd0 u-boot partition. It only compiles u-boot 2019 and output the binary. This binary is part of mtd0, but should *never* be flashed raw to mtd0. I did *not* test this binary on target.

- **u-boot-fw-utils** compiled from the same repo as u-boot 2019.07
This replaces the default openembedded-core u-boot-fw-utils (2016.03)

- **u-boot-script**
This has been added so that a /boot.scr is compiled and added to the bootfs. The stock u-boot (2019 version) will always looks for a /boot.scr in the bootfs that it runs prior to trying other bootmeasures. This bootscript defines what u-boot needs to do in order to load and run linux. This solves the problem where a user needs downgrade u-boot and solves the issue of having to invoke `env -a default`, `saveenv` and `reset`, as documented here: https://wiki.rdkcentral.com/display/RDK/Turris+Omnia+Reference+Platform%3A++Flashing+Instruction.

The second commit adds the generation of a wic image. This wic image is formatted similar to the `openwrt-18.06.2-mvebu-cortexa9-turris-omnia-sysupgrade.img.gz` in https://wiki.rdkcentral.com/display/RDK/Turris+Omnia+Reference+Platform%3A++Flashing+Instruction. With this commit, the `sysupgrade openwrt-18.06.2-mvebu-cortexa9-turris-omnia-sysupgrade.img.gz` in this document can be replaced with `sysupgrade rdk-generic-broadband-image-turris.wic`, immediately flashing RDK-B to the board instead of flashing OpenWRT first. It ensures that a user does not have to go through the manual partitioning steps in chapter `Flashing RDKB image(A Yocto Project based Distro)`. A "disadvantage" is there there now is no OpenWRT flashed to the board anymore.

In addition to the sysupgrade image generation, I have modified the openwrt medkit image so that it contains a boot.scr in bootfs so that u-boot is able to boot into the medkit automatically. I also added a startup script that automatically mount the usb and performs a `sysupgrade` on boot. As a result, one can populate the usb with this new medkit image and the newly generated wic image (sysupgrade image) and perform the 4-led upgrade without the need for user interaction. The 4-led upgrade now goes as follows:
1) perform 4-led upgrade with usb plugged in, containing the new medkit and the sysupgrade image
2) rescue image will find and install the medkit image on mmc flash and reboot
3) since the medkit image now has a boot.scr in bootfs, u-boot 2019 uses this to boot into the medkit image automatically: no more need for manually loading kernel ao in RAM and running them manually.
4) the medkit's startup scripts run, including the new startup script that mount the usb device and performs a sysupgrade using the wic image.
5) The wic image is flashed to mmc and the system reboot.
6) The new bootfs also contains a boot.scr. U-boot again uses this to boot into the board. RDK-B now boots.

No more user interaction, neither via ssh nor via serial.

Constraints:
* Upgrade procedure untested with u-boot 2015.10.
* U-boot 2019 binary untested: assumed that CZ.NIC has a working `omnia-2019` branch in their github.
* The approach of having u-boot find a boot.scr in a bootfs works fine when running a single bootfs (one "bank"). The moment there is a move to two banks (two rootfs and two bootfs), this bootscript is undesirable since it varies depending on what bootfs it is a part of. This bootscript is thus a solution for moving from TurrisOs to RDK-B, but should not be used for dualbank solutions.

### CODE REVIEW

**Comment by mhughesacn** [comment]
Hi @fifalars.  Please will you remove the new LICENSE file because this is not consistent with how RDK organises its licenses.  I believe the license file is being used for LIC_FILES_CHKSUM, so it should be possible
(1) In the case of utils, to use the equivalent in the SRC_URI repo (actually the README in https://gitlab.nic.cz/turris/turris-omnia-uboot), and 
(2) In the case of the script recipe which doesn't have an external SRC_URI, perhaps add a license line to the README and use it.  (In any case you are already using this local README another recipe.)
Thanks,
Martin Hughes, RDK CMF Compliance Team

**Comment by fifalars** [comment]
Hi Martin,
Thanks for taking a look. With the new push, I removed the LICENCE file and changed the chksum file to README.
> (In any case you are already using this local README another recipe.)
Those are the READMEs from the u-boot source code being pulled in.
Kind regards,
Lars

**Comment by manigandanj** [comment]
CMF team,
Build issue to be addressed with another pull request. please waive "Component build" check failure.

**Comment by jamcoole** [comment]
Component Build status set as requested, please ensure new PR is created/merged as soon as possible once this change is merged

**Pull request merged**
