### PR TITLE
Fixing OpenSync core component SRC_URI assignment

### PR DESCRIPTION
**Pull request by manigandanj**
Signed-off-by: Manigandan Gopalakrishnan <manigandan.gopalakrishnan@ltts.com>

### CODE REVIEW

**Review by scthunderbolt — CHANGES_REQUESTED** [review]
What does Restoring core component patches  mean?

Is this patch not needed anymore in the new version?
0007-Fix-conflict-with-yocto-kernel-tools-kconfiglib.patch

Please put more detail in the commit msg.

**Comment by scthunderbolt** [comment]
Also please remove any patches that is no longer needed.

**Comment by manigandanj** [comment]
> Also please remove any patches that is no longer needed.

I have removed unused patch file.

**Comment by manigandanj** [comment]
> What does Restoring core component patches mean?
> 
> Is this patch not needed anymore in the new version?
> 0007-Fix-conflict-with-yocto-kernel-tools-kconfiglib.patch
> 
> Please put more detail in the commit msg.

I have added few more detail in this commit message https://github.com/rdkcentral/meta-turris/pull/232/commits/d90164dc97bbf1b8e0bde4ec6b72ca5e7ab754c0. Please tell me if i need to add elaborating details.

**Review by scthunderbolt — APPROVED** [review]

**Review by rajkumar154 — APPROVED** [review]

**Pull request merged**
