### PR TITLE
Opensync version upgrade to 1.4.0

### PR DESCRIPTION
**Pull request by manigandanj**
Signed-off-by: manigandan.gopalakrishnan <manigandan.gopalakrishnan@ltts.com>

### CODE REVIEW

**Comment by scthunderbolt** [comment]
Further investigations show that the error is environment related, specifically the path of the workspace.

The error is confirmed to occur when the path of the workspace is either:
"
/home/jenkins/jenkinsroot/workspace/build-turris-broadband-nosrc/build-turris-broadband-nosrc
"
or
"
/home/jenkins/jenkinsroot/workspace/build-turris-broadband-nosrc/EXEC_0
"

However it does NOT occur with the following path and the build proceeded to conclusion:
"
/home/jenkins/jenkinsroot/workspace/build-turris-broadband-nosrc
"

**Comment by scthunderbolt** [comment]
The problem is only observed in osync 1.4; osync 1.2 is OK.

Looks like the problem is in the configure stage, using python3-kconfig, which is new to 1.4.

This would have to be fixed by Plume.

**Comment by scthunderbolt** [comment]
Analysis and investigations of the errors show that they are due to the shebang of the python3-kconfiglib `genconfig` script exceeding the standard linux 128 bytes, due to the path fo the build workspace.

So a truncated shebang to 128 bytes tried to execute and results in erratic errors. 

However since the 128 byte shebang length is compiled into the kernel, there is no easy way around this problem.

**Comment by manigandanj** [comment]
@scthunderbolt , shall we try with kernel patch increasing shebang length from 128 to 192 ?

**Pull request merged**
