### PR TITLE
Adding wireless-tools recipe to dunfell upgrade

### PR DESCRIPTION
**Pull request by DeekshaCS**
Signed-off-by: deekshacs <deeksha.cs@Ltts.com>

### CODE REVIEW

**Comment by mhughesacn** [comment]
Hi DeekshaCS,
1. Please confirm that the recipe here is only used to create a standalone executable (iwconfig) and that there is no library which is linked with any other code. This matters because the code in wireless-tools is mostly GPL.
2. Please include a source in the patch header.  Ideally, Date:, From: and if the patch is not your own, a Source: field.
Thank you,
Martin Hughes, RDK CMF Compliance Team

**Comment by manigandanj** [comment]
Hello @mhughesacn , 
We want iwconfig utility for WiFi HAL APIs(soon we will replace with "iw" command). we are not linking library to any code.

Openembedded-core(dunfell version) is not providing wireless-tools recipe, so we copied from openembedded-core(morty version). Patches did not have headers in openembedded-core(morty).

Kindly suggest us on how to resolve this.

**Comment by mhughesacn** [comment]
Thanks Manigandan.  iwconfig is OK so long as it is used standalone.  Please will you update the patch header to include a "Source: " field and give the source as a URL or "copied from openembedded-core (morty branch)".  I think this is enough as the recipe is MIT licensed and without a header, and NOTICE mentions openembedded-core.  The patch is presumed to have a GPL license like the source repo and you are required to give credit.

**Comment by manigandanj** [comment]
Required recipe is added in another meta layer. So, closing this Pull request.

**Pull request closed without merging**
